cloud_sources:
  - name: tilt_scan_cloud_filtered
    frame_subsample: 1
    point_subsample: 1
    sensor_frame: shoulder_tilting_laser
    dynamic_publish: true
    static_publish: true
    dynamic_until_static_publish: true
    dynamic_buffer_size: 25
  - name: base_laser_cloud_filtered
    sensor_frame: laser_front_left
    frame_subsample: 1
    point_subsample: 1
    dynamic_publish: true
